version: '3'
services:
    client-frontend:
        image: mihaiburlaciuc/budget-app-client-frontend
        build: ./client-frontend
        command: "npm start"
        stdin_open: true
        ports:
         - "3001:3000"
    
    backend:
        image: mihaiburlaciuc/budget-app-node
        build: ./backend
        command: "node server.js"
        ports:
         - "8081:8080"
        depends_on: 
         - "mongo"
         
    mongo: 
        image: "mongo"
        ports:
         - "27018:27017"
    
   


        