version: '3'
services:
    client-frontend:
        image: mihaiburlaciuc/budget-app-client-frontend
        build: ./client-frontend
        command: "npm start"
        volumes:
            - ./client-frontend:/app/
            - '/app/node_modules'
        stdin_open: true
        ports:
         - "3000:3000"

    admin-frontend:
        image: mihaiburlaciuc/budget-app-admin-frontend
        build: ./admin-frontend
        command: "npm start"
        volumes:
            - ./admin-frontend:/app/
            - '/app/node_modules'
        stdin_open: true
        ports:
            - "3001:3000"
    
    backend:
        image: mihaiburlaciuc/budget-app-node
        build: ./backend
        command: "nodemon server.js"
        volumes:
            - ./backend:/app/
            - /usr/app/node_modules
        ports:
         - "8080:8080"
        depends_on: 
         - "mongo"
         
    mongo: 
        image: "mongo"
        ports:
         - "27018:27017"

    prometheus:
        image: "prom/prometheus"
        ports:
         - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus/
        
    grafana:
        image: "grafana/grafana"
        ports: 
         - "3002:3000"

        