version: '3'
services:
    client-frontend:
        image: mihaiburlaciuc/budget-app-client-frontend
        build: ./client-frontend
        command: "npm start"
        stdin_open: true
        ports:
         - "3000:3000"
        networks:
            - webnet

    admin-frontend:
        image: mihaiburlaciuc/budget-app-admin-frontend
        build: ./admin-frontend
        command: "npm start"
        stdin_open: true
        ports:
            - "3001:3000"
        networks:
            - webnet
    
    backend:
        image: mihaiburlaciuc/budget-app-node
        build: ./backend
        command: "nodemon server.js"
        ports:
         - "8080:8080"
        depends_on: 
         - "mongo"
        networks:
            - webnet
         
    mongo: 
        image: "mongo"
        ports:
         - "27018:27017"
        networks:
            - webnet

    prometheus:
        image: "prom/prometheus"
        ports:
         - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus/
        networks:
            - webnet
        
    grafana:
        image: "grafana/grafana"
        ports: 
         - "3002:3000"
        networks:
            - webnet
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8081:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - webnet

networks:
    webnet:

        