version: '3'
services:
    client-frontend:
        image: mihaiburlaciuc/budget-app-client-frontend
        build: ./client-frontend
        command: "npm start"
        volumes:
            - ./client-frontend:/app/
            - '/app/node_modules'
        stdin_open: true
        ports:
         - "3000:3000"
    
    backend:
        image: mihaiburlaciuc/budget-app-node
        build: ./backend
        command: "nodemon server.js"
        volumes:
            - ./backend:/app/
            - /usr/app/node_modules
        ports:
         - "8080:8080"
        depends_on: 
         - "mongo"
         
    mongo: 
        image: "mongo"
        ports:
         - "27018:27017"
    
   


        