version: '3'
services:
    backend:
        image: mihaiburlaciuc/budget-app-node
        build: .
        command: "node server.js"
        ports:
         - "8080:8080"
        depends_on: 
         - "mongo"
    mongo: 
        image: "mongo"
        ports:
         - "27017:27017"

        